target: release/current
base: pistomp-v3
merge:
  - feat/blend-control-viz
  - feat/deploy-script
  - feat/hardware-deps
  - feat/lcd-splash
  - feat/lcd-text-scroll
  - feat/multi-wifi
  - feat/new-tuner
  - feat/on-device-config-editor
  - feat/sync-pedalboards
  - fix/version-script-main
  - simplify/blend-mode
  - test/blend-mode
  - test/websocket-parameter-set
  - feat/bouquet
