# aliass for common pi-stomp operations (only intended to aid the memory of humans)
alias ps-restart='sudo systemctl restart mod-ala-pi-stomp'
alias ps-stop='sudo systemctl stop mod-ala-pi-stomp'
alias ps-run='$HOME/pi-stomp/modalapistomp.py'
alias ps-journal='sudo journalctl -f -u mod-ala-pi-stomp'
