from typing import Any

class SSD1306_I2C:
    width: int
    height: int
    rotation: int
    def __init__(self, width: int, height: int, i2c: Any) -> None: ...
    def pixel(self, x: int, y: int, color: int) -> None: ...
    def show(self) -> None: ...
    def fill(self, color: int) -> None: ...
