from typing import Any

class DigitalOutputDevice:
    def __init__(self, pin: int | None) -> None: ...
    def on(self) -> None: ...
    def off(self) -> None: ...

class LED:
    def __init__(self, pin: int) -> None: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def toggle(self) -> None: ...
    def blink(self, on_time: float = 1, off_time: float = 1, n: int | None = None, background: bool = True) -> None: ...
    is_lit: bool

class Button:
    def __init__(self, pin: int | None, *, pull_up: bool = True, bounce_time: float | None = None) -> None: ...
    def wait_for_press(self, timeout: float | None = None) -> bool: ...
    def wait_for_release(self, timeout: float | None = None) -> bool: ...
    def close(self) -> None: ...
    is_pressed: bool
    when_pressed: Any | None
