# This file provides some default configuration for the system
# Most of this configuration can be overriden by pedalboard specific configuration.  To accomplish that, add
# a file, named config.yml to the pedalboard directory (ie. ~/data/.pedalboards/<pedalboard-name>)

---
hardware:
  # Hardware version (1.0 for original pi-Stomp, 2.0 for pi-Stomp Core)
  version: 2.0

  # midi definition
  #  channel: midi channel used for midi messages
  midi:
    channel: 14

  # footswitches definition
  #   id: integer identifier and physical position (required for each footswitch)
  #   bypass: relay(s) to toggle (LEFT, RIGHT or LEFT_RIGHT)
  #   color: color to use for enable status halo on LCD
  #   debounce_input: debounce chip pin to which switch is connected
  #   gpio_input: gpio pin if not using debounce
  #   gpio_output: gpio pin used to drive indicator (LED, etc.)
  #   midi_CC: msg to send (0 - 127)
  #   longpress: The name of a handler method to call when switch is long-pressed
  #
  footswitches:
  - id: 0
    debounce_input: 0
    gpio_output: 0
    midi_CC: 61
    longpress: next_snapshot
  - id: 1
    debounce_input: 1
    gpio_output: 13
    midi_CC: 62
    longpress: previous_snapshot
    color: lime
  - id: 2
    debounce_input: 2
    gpio_output: 26
    midi_CC: 63
    longpress: toggle_tap_tempo_enable
    tap_tempo: set_mod_tap_tempo
    color: blue

  # analog_controllers:
  # Each control definition is a list which starts with the adc_input
  # adc_input: <integer>          The analog input to which the control is connected (required)
  # id: <integer>                 The id and position on the screen (starting with 0 on the left)
  # type: <KNOB | EXPRESSION>     The control type, used to represent the control on the screen (optional)
  # midi_CC: <integer>            The MIDI CC message to be sent when the control is adjusted (optional)
  # autosync: <true | false>      Whether to send current value on pedalboard load (optional, default: false)
  #
  analog_controllers:
  #- adc_input: 7
  #  id: 0
  #  midi_CC: 77
  #  type: EXPRESSION
  #  autosync: true
  - adc_input: 0
    id: 1
    midi_CC: 70
    type: KNOB
  - adc_input: 1
    id: 2
    midi_CC: 71
    type: KNOB
