# This file provides some default configuration for the system
# Unless you have altered the hardware or really know what you're doing, changing this file is not recommended
# and can result in a malfunctioning system.
# Most of this configuration can be overriden by pedalboard specific configuration.  To accomplish that, add
# a file, named config.yml to the pedalboard directory (ie. /var/modep/pedalboards/<pedalboard-name>)

---
hardware:
  version: 1.0
  midi:
    channel: 14
  footswitches:
  - id: 0
    bypass: LEFT_RIGHT
    preset: UP
    midi_CC: None
  - id: 1
    midi_CC: 62
  - id: 2
    midi_CC: 63
