# This file provides some default configuration for the system
# Most of this configuration can be overriden by pedalboard specific configuration.  To accomplish that, add
# a file, named config.yml to the pedalboard directory (ie. /var/modep/pedalboards/<pedalboard-name>)

---
hardware:
  # Hardware version (1.0 for original pi-Stomp, 2.0 for pi-Stomp Core)
  version: 2.0

  # midi definition
  #  channel: midi channel used for midi messages
  midi:
    channel: 14

  # footswitches definition
  #   bypass: relay(s) to toggle (LEFT, RIGHT or LEFT_RIGHT)
  #   debounce_input: debounce chip pin to which switch is connected
  #   disable: disable the switch
  #   gpio_input: gpio pin if not using debounce
  #   gpio_output: gpio pin used to drive indicator (LED, etc.)
  #   id: integer identifier
  #   midi_CC: msg to send (0 - 127 or None)
  #
  footswitches:
  - id: 0
    debounce_input: 2
    midi_CC: 60
    bypass: LEFT
    preset: UP
  - id: 1
    debounce_input: 3
    midi_CC: 62
  - id: 2
    debounce_input: 4
    midi_CC: 63

  # analog control definition
  #   adc_input: adc chip pin to which control is connected
  #   disable: disable the control
  #   midi_CC: msg to send (0 - 127 or None)
  #   threshold: minimum value change to trigger a midi msg (16 default, 1024 full scale)
  #   type: control type (KNOB, EXPRESSION)
  #
  #analog_controllers:
  #- adc_input: 0
  #  midi_CC: 70
