from typing import Callable, Sequence

class MidiOut:
    def open_port(self, port: int = 0, port_name: str = "") -> None: ...
    def open_virtual_port(self, port_name: str = "") -> None: ...
    def close_port(self) -> None: ...
    def is_port_open(self) -> bool: ...
    def get_ports(self) -> list[str]: ...
    def get_port_count(self) -> int: ...
    def get_port_name(self, port: int) -> str: ...
    def send_message(self, message: Sequence[int]) -> None: ...

class MidiIn:
    def open_port(self, port: int = 0, port_name: str = "") -> None: ...
    def open_virtual_port(self, port_name: str = "") -> None: ...
    def close_port(self) -> None: ...
    def is_port_open(self) -> bool: ...
    def get_ports(self) -> list[str]: ...
    def get_port_count(self) -> int: ...
    def get_port_name(self, port: int) -> str: ...
    def get_message(self) -> tuple[list[int], float] | None: ...
    def set_callback(self, func: Callable[[list[int], float], None]) -> None: ...
    def cancel_callback(self) -> None: ...

class RtMidiError(Exception): ...
class InvalidPortError(RtMidiError): ...
class InvalidUseError(RtMidiError): ...
class NoDevicesError(RtMidiError): ...
class MemoryAllocationError(RtMidiError): ...
class SystemError(RtMidiError): ...
class UnsupportedOperationError(RtMidiError): ...
