class SharedMemory:
    name: str | None
    _name: str
    def __init__(self, name: str | None = None, create: bool = False, size: int = 0) -> None: ...
    def close(self) -> None: ...
    def unlink(self) -> None: ...
    buf: memoryview
    size: int
